routes/web.php
<?php

Auth::routes();

//================== This is for Front End ====================

// Landing Page
Route::get('/', function () {
	return view('front.landing');
});

// Blog
Route::get('/blog', 'BlogController@index');
Route::get('/blog/search', 'BlogController@search')->name('blog.search');
Route::get('/blog/luck', 'BlogController@luck')->name('blog.luck');
Route::get('/blog/category/{slug}', 'BlogController@category')->name('blog.category');
Route::get('/blog/tag/{slug}', 'BlogController@tag')->name('blog.tag');
Route::get('/blog/author/{id}', 'BlogController@author')->name('blog.author');
Route::get('/blog/{slug}', 'BlogController@show')->name('blog.details');

Route::get('/about', function () {
	return view('front.about');
});
Route::get('/contact', function () {
	return view('front.contact');
});

// Quick Links
Route::get('/license', function () {
	return view('front.license');
});
Route::get('/privacy-policy', function () {
	return view('front.privacy-policy');
});
Route::get('/contribute', function () {
	return view('front.contribute');
});

// Hall of Fame
Route::get('/report-bug', function () {
	return view('front.report-bug');
});
Route::get('/heroes', function () {
	return view('front.heroes');
});
Route::get('/patched', function () {
	return view('front.patched');
});



//================== This is for Back End ====================

Route::group(['middleware' => 'auth'], function()
{
	Route::get('/webmanager', 'WebManagerController@index')->name('webmanager');

	Route::get('/webmanager/posts/archived', 'PostsController@archived')->name('webmanager.posts.archived');
	Route::get('/webmanager/posts/restore/{id}', 'PostsController@restore')->name('webmanager.posts.restore');
	Route::delete('/webmanager/posts/clean/{id}', 'PostsController@clean')->name('webmanager.posts.clean');
	Route::delete('/webmanager/posts/massclean', 'PostsController@massclean')->name('webmanager.posts.massclean');

	Route::prefix('webmanager')->name('webmanager.')->group(function() {
   		Route::resource('tags','TagsController');
	});

	Route::prefix('webmanager')->name('webmanager.')->group(function() {
   		Route::resource('categories','CategoriesController');
	});

	Route::prefix('webmanager')->name('webmanager.')->group(function() {
   		Route::resource('posts','PostsController');
	});

	Route::prefix('webmanager')->name('webmanager.')->group(function() {
   		Route::resource('users','UsersController');
	});

	Route::prefix('webmanager')->name('webmanager.')->group(function() {
   		Route::resource('profiles','ProfilesController');
	});

	Route::prefix('webmanager')->name('webmanager.')->group(function() {
   		Route::resource('sites','SitesController');
	});

});

resources/views/admin-template/footer.blade.php
<footer class="main-footer">
	<div class="footer-left">
		Copyleft &copy; 2020 <div class="bullet"></div> Made with <svg class="mx-1" height="16" width="16" viewBox="0 0 47.5 47.5" style="enable-background:new 0 0 47.5 47.5"><clipPath id="clipPath16" clipPathUnits="userSpaceOnUse"><path id="path18" d="M0 38H38V0H0V38z" /></clipPath></defs><g transform="matrix(1.25,0,0,-1.25,0,47.5)" id="g10"><g id="g12"><g clip-path="url(#clipPath16)" id="g14"><g transform="translate(36.8848,25.1665)" id="g20"><path id="path22" style="fill:#be1931;fill-opacity:1;fill-rule:nonzero;stroke:none" d="m0 0c0 5.45-4.418 9.868-9.867 9.868-3.308.0-6.227-1.633-8.018-4.129-1.79 2.496-4.71 4.129-8.017 4.129-5.45.0-9.868-4.418-9.868-9.868.0-.772.098-1.52.266-2.241 1.371-8.512 10.835-17.494 17.619-19.96 6.783 2.466 16.249 11.448 17.617 19.96C-.098-1.52.0-.772.0.0" /></g></g></g></g></svg> by <a href="{{ url('') }}" target="_blank">{{ App\Sites::first()->sitename }}</a>
	</div>
	<div class="footer-right">	
	</div>
</footer>

resources/views/admin-template/header.blade.php
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>{{ App\Sites::first()->sitename }} - @yield('title')</title>
  <link rel="apple-touch-icon" sizes="180x180" href="{{asset('front/img/favicon/apple-touch-icon.png')}}">
  <link rel="icon" type="image/png" sizes="32x32" href="{{asset('front/img/favicon/favicon-32x32.png')}}">
  <link rel="icon" type="image/png" sizes="16x16" href="{{asset('front/img/favicon/favicon-16x16.png')}}">
  <link rel="manifest" href="{{asset('front/img/favicon/site.webmanifest')}}">
  <link rel="mask-icon" href="{{asset('front/img/favicon/safari-pinned-tab.svg')}}" color="#5bbad5">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">

  <!-- General CSS Files -->
  <link rel="stylesheet" href="{{ asset('assets/modules/bootstrap/css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/modules/fontawesome/css/all.min.css') }}">

  <!-- CSS Libraries -->
  <link rel="stylesheet" href="{{ asset('assets/modules/datatables/datatables.min.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/modules/datatables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/modules/datatables/Select-1.2.4/css/select.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/modules/select2/dist/css/select2.min.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/modules/jquery-selectric/selectric.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/modules/summernote/summernote-bs4.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/modules/codemirror/lib/codemirror.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/modules/codemirror/theme/duotone-dark.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/modules/chocolat/dist/css/chocolat.css') }}">

  <!-- Template CSS -->
  <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/css/components.css') }}">
<!-- Start GA -->
<!-- <script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-94034622-3');
</script> -->
<!-- /END GA -->

<!-- CKEditor Libraries -->
<script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>


<!-- Page Specific JS File -->
<!-- <script src="{{ asset('assets/js/page/forms-advanced-forms.js') }}"></script> -->


</head>

resources/views/admin-template/js.blade.php
  <!-- General JS Scripts -->
  <script src="{{ asset('assets/modules/jquery.min.js') }}"></script>
  <script src="{{ asset('assets/modules/popper.js') }}"></script>
  <script src="{{ asset('assets/modules/tooltip.js') }}"></script>
  <script src="{{ asset('assets/modules/bootstrap/js/bootstrap.min.js') }}"></script>
  <script src="{{ asset('assets/modules/nicescroll/jquery.nicescroll.min.js') }}"></script>
  <script src="{{ asset('assets/modules/moment.min.js') }}"></script>
  <script src="{{ asset('assets/js/stisla.js') }}"></script>
  
  <!-- JS Libraries -->
  <script src="{{ asset('assets/modules/jquery-pwstrength/jquery.pwstrength.min.js') }}"></script>
  <script src="{{ asset('assets/modules/cleave-js/dist/cleave.min.js') }}"></script>
  <script src="{{ asset('assets/modules/cleave-js/dist/addons/cleave-phone.us.js') }}"></script>
  <script src="{{ asset('assets/modules/datatables/datatables.min.js') }}"></script>
  <script src="{{ asset('assets/modules/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js') }}"></script>
  <script src="{{ asset('assets/modules/datatables/Select-1.2.4/js/dataTables.select.min.js') }}"></script>
  <script src="{{ asset('assets/modules/jquery-ui/jquery-ui.min.js') }}"></script>
  <script src="{{ asset('assets/modules/select2/dist/js/select2.full.min.js') }}"></script>
  <script src="{{ asset('assets/modules/jquery-selectric/jquery.selectric.min.js') }}"></script>
  <script src="{{ asset('assets/modules/summernote/summernote-bs4.js') }}"></script>
  <script src="{{ asset('assets/modules/codemirror/lib/codemirror.js') }}"></script>
  <script src="{{ asset('assets/modules/codemirror/mode/javascript/javascript.js') }}"></script>
  <script src="{{ asset('assets/modules/chocolat/dist/js/jquery.chocolat.min.js') }}"></script>

  <!-- Page Specific JS File -->
  <!-- <script src="{{ asset('assets/js/page/forms-advanced-forms.js') }}"></script> -->
  <script src="{{ asset('assets/js/page/modules-datatables.js') }}"></script>
  
  <!-- Template JS File -->
  <script src="{{ asset('assets/js/scripts.js') }}"></script>
  <script src="{{ asset('assets/js/custom.js') }}"></script>

  <!-- Script JS CKEditor -->
  <script>
    $(document).ready(function(){
      $('.editor').each(function(e){
        CKEDITOR.replace( this.id, {
          language: 'en',
          filebrowserImageBrowseUrl: '/filemanager?type=Images',
          filebrowserImageUploadUrl: '/filemanager/upload?type=Images&_token=',
          filebrowserBrowseUrl: '/filemanager?type=Files',
          filebrowserUploadUrl: '/filemanager/upload?type=Files&_token='
        });
      });
    });
  </script>

resources/views/admin-template/logout-modal.blade.php
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>

resources/views/admin-template/page.blade.php
<!DOCTYPE html>
<html lang="en">

<!-- Header -->
@include('admin-template.header')

<body>
  <div id="app">
    <div class="main-wrapper main-wrapper-1">
      <div class="navbar-bg"></div>

      <!-- Topbar -->
      @include('admin-template.topbar')

      <!-- Sidebar -->
      @include('admin-template.sidebar')

      <!-- Main Content -->
      @yield('content')

      <!-- Footer -->
      @include('admin-template.footer')

    </div>
  </div>

  <!-- JavaScript -->
  @include('admin-template.js')

</body>
</html>

resources/views/admin-template/sidebar.blade.php
<div class="main-sidebar sidebar-style-2">
  <aside id="sidebar-wrapper">
    <div class="sidebar-brand">
      <a href="{{ route('webmanager') }}">{{ App\Sites::first()->sitename }}</a>
    </div>
    <div class="sidebar-brand sidebar-brand-sm">
    </div>
    <ul class="sidebar-menu">
      <li class="@yield('activedashboard')"><a class="nav-link" href="{{ route('webmanager') }}"><i class="fas fa-fire"></i> <span>Dashboard</span></a>
      </li>
      <li class="menu-header">Artikel</li>
      <li class="dropdown @yield('activeposts')">
        <a href="#" class="nav-link has-dropdown"><i class="fas fa-file-alt"></i><span>Posts</span></a>
        <ul class="dropdown-menu">
          <li class="@yield('active_p_new')"><a class="nav-link" href="{{ route('webmanager.posts.create') }}">New Post</a></li>
          <li class="@yield('active_p_lists')"><a class="nav-link" href="{{ route('webmanager.posts.index') }}">Lists</a></li>
          <li class="@yield('active_p_archived')"><a class="nav-link" href="{{ route('webmanager.posts.archived') }}">Archived</a></li>
        </ul>
      </li>
      @if(Auth::user()->level == 1)
      <li class="dropdown @yield('activecategories')">
        <a href="#" class="nav-link has-dropdown"><i class="fas fa-book"></i><span>Category</span></a>
        <ul class="dropdown-menu">
          <li class="@yield('active_c_add')"><a class="nav-link" href="{{ route('webmanager.categories.create') }}">Add Kategori</a></li>
          <li class="@yield('active_c_lists')"><a class="nav-link" href="{{ route('webmanager.categories.index') }}">Lists</a></li>
        </ul>
      </li>
      <li class="dropdown @yield('activetags')">
        <a href="#" class="nav-link has-dropdown"><i class="fas fa-bookmark"></i><span>Tags</span></a>
        <ul class="dropdown-menu">
          <li class="@yield('active_t_add')"><a class="nav-link" href="{{ route('webmanager.tags.create') }}">Add Tags</a></li>
          <li class="@yield('active_t_lists')"><a class="nav-link" href="{{ route('webmanager.tags.index') }}">Lists</a></li>
        </ul>
      </li>
      @endif
      <li class="menu-header">Settings</li>
      @if(Auth::user()->level == 1)
      <li class="dropdown @yield('activeaccounts')">
        <a href="#" class="nav-link has-dropdown"><i class="fas fa-users-cog"></i><span>Accounts</span></a>
        <ul class="dropdown-menu">
          <li class="@yield('active_a_create')"><a class="nav-link" href="{{ route('webmanager.users.index') }}">Create</a></li>
          <li @yield('active_a_lists')><a class="nav-link" href="{{ route('webmanager.users.index') }}">Lists</a></li>
        </ul>
      </li>
      @endif
      <li class="@yield('activeprofile')"><a class="nav-link" href="{{ route('webmanager.profiles.index') }}"><i class="fas fa-user-cog"></i> <span>Profile</span></a>
      </li>
      @if(Auth::user()->level == 1)
      <li class="@yield('activeconfigurations')"><a class="nav-link" href="{{ route('webmanager.sites.index') }}"><i class="fas fa-sliders-h"></i> <span>Site Configurations</span></a>
      </li>
      @endif
    </ul>
  </aside>
</div>

resources/views/admin-template/topbar.blade.php
      <nav class="navbar navbar-expand-lg main-navbar">
        <form class="form-inline mr-auto">
          <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
            <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
          </ul>
        </form>
        <ul class="navbar-nav navbar-right">
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
              <img alt="image" src="{{ asset(App\User::findorfail(Auth::user()->id)->avatar) }}" class="rounded-circle mr-1" style="width: 30px; height: 30px;">
                <div class="d-sm-none d-lg-inline-block">{{ Auth::user()->name }}</div></a>
            <div class="dropdown-menu dropdown-menu-right">
              <a href="{{ route('webmanager.profiles.index') }}" class="dropdown-item has-icon">
                <i class="far fa-user"></i> Profile
              </a>
              @if(Auth::user()->level == 1)
              <a href="{{ route('webmanager.sites.index') }}" class="dropdown-item has-icon">
                <i class="fas fa-cog"></i> Settings
              </a>
              @endif
              <div class="dropdown-divider"></div>
              <a class="dropdown-item has-icon text-danger" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                <i class="fas fa-sign-out-alt"></i>{{ __('Log Out') }}
              </a>
              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
              </form>
            </div>
          </li>
        </ul>
      </nav>