routes/web.php
<?php

Auth::routes();

//================== This is for Front End ====================

// Landing Page
Route::get('/', function () {
	return view('front.landing');
});

// Blog
Route::get('/blog', 'BlogController@index');
Route::get('/blog/search', 'BlogController@search')->name('blog.search');
Route::get('/blog/luck', 'BlogController@luck')->name('blog.luck');
Route::get('/blog/category/{slug}', 'BlogController@category')->name('blog.category');
Route::get('/blog/tag/{slug}', 'BlogController@tag')->name('blog.tag');
Route::get('/blog/author/{id}', 'BlogController@author')->name('blog.author');
Route::get('/blog/{slug}', 'BlogController@show')->name('blog.details');

Route::get('/about', function () {
	return view('front.about');
});
Route::get('/contact', function () {
	return view('front.contact');
});

// Quick Links
Route::get('/license', function () {
	return view('front.license');
});
Route::get('/privacy-policy', function () {
	return view('front.privacy-policy');
});
Route::get('/contribute', function () {
	return view('front.contribute');
});

// Hall of Fame
Route::get('/report-bug', function () {
	return view('front.report-bug');
});
Route::get('/heroes', function () {
	return view('front.heroes');
});
Route::get('/patched', function () {
	return view('front.patched');
});



//================== This is for Back End ====================

Route::group(['middleware' => 'auth'], function()
{
	Route::get('/webmanager', 'WebManagerController@index')->name('webmanager');

	Route::get('/webmanager/posts/archived', 'PostsController@archived')->name('webmanager.posts.archived');
	Route::get('/webmanager/posts/restore/{id}', 'PostsController@restore')->name('webmanager.posts.restore');
	Route::delete('/webmanager/posts/clean/{id}', 'PostsController@clean')->name('webmanager.posts.clean');
	Route::delete('/webmanager/posts/massclean', 'PostsController@massclean')->name('webmanager.posts.massclean');

	Route::prefix('webmanager')->name('webmanager.')->group(function() {
   		Route::resource('tags','TagsController');
	});

	Route::prefix('webmanager')->name('webmanager.')->group(function() {
   		Route::resource('categories','CategoriesController');
	});

	Route::prefix('webmanager')->name('webmanager.')->group(function() {
   		Route::resource('posts','PostsController');
	});

	Route::prefix('webmanager')->name('webmanager.')->group(function() {
   		Route::resource('users','UsersController');
	});

	Route::prefix('webmanager')->name('webmanager.')->group(function() {
   		Route::resource('profiles','ProfilesController');
	});

	Route::prefix('webmanager')->name('webmanager.')->group(function() {
   		Route::resource('sites','SitesController');
	});

});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'name', 'email', 'password', 'level', 'avatar', 'bio',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function index()
    {
        $users =  User::paginate();
        return view('admin.users.index', compact('users'));
    }

    public function create()
    {
        return view('admin.users.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|min:3|max:40',
            'email' => 'required|email',
            'level' => 'required',
            'password' => 'required'
        ]);

        User::create([
            'name' => $request->name,
            'email' => $request->email,
            'level' => $request->level,
            'password' => bcrypt($request->password),
            'bio' => 'Ini adalah bio dari '.$request->name,
            'avatar' => 'assets/img/avatar/avatar-1.png'
        ]);

        return redirect()->back()->with('success', 'New User Saved!');
    }

    public function edit($id)
    {
        $users = User::findorfail($id);
        return view('admin.users.edit', compact('users'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|min:3|max:40',
            'email' => 'required|email',
            'level' => 'required'
        ]);

        if ($request->input('password')) {
            $user_data = [
                'name' => $request->name,
                'email' => $request->email,
                'level' => $request->level,
                'password' => bcrypt($request->password)
            ];
        } else {
            $user_data = [
                'name' => $request->name,
                'email' => $request->email,
                'level' => $request->level
            ];
        }
        User::whereId($id)->update($user_data);
        return redirect()->route('webmanager.users.index')->with('status', 'User Data Updated!');
    }

    public function destroy($id)
    {
        $user = User::findorfail($id);
        $user->delete();
        return redirect()->route('webmanager.users.index')->with('status', 'User Deleted!');
    }
}

resources/views/admin/users/create.blade.php
@extends('admin-template.page')
@section('title', 'Buat Akun')
@section('activeaccounts', 'active')
@section('active_a_create', 'active')
@section('content')
<!-- Page Heading -->
<div class="main-content">
  <section class="section">
    <div class="section-header">
      <h1>Buat Akun</h1>
    </div>
    <div class="section-body">
      <div class="row">
        <div class="col-12">
          <div class="card">
            @if (session('success'))
            <div class="alert alert-success" role="alert">
              {{ session('success') }}
            </div>
            @endif
            @error('success')
            <div class="alert alert-danger" role="alert">
              {{ $message }}
            </div>
            @enderror
            <div class="card-header py-3">
              <a href="{{ route('webmanager.users.index') }}" class="btn btn-sm btn-primary btn-icon btn-icon-left">
                <span class="icon text-white-50">
                  <i class="fas fa-chevron-circle-left"></i>
                </span>
                <span class="text">Back</span>
              </a>  
            </div>
            <div class="card-body">
              <form method="POST" action=" {{ route('webmanager.users.store') }} ">
                @csrf
                <div class="form-group">
                  <label>Nama</label>
                  @if (session('status'))
                  <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                  </div>
                  @endif
                  @error('name')
                  <div class="alert alert-danger" role="alert">
                    {{ $message }}
                  </div>
                  @enderror
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <div class="input-group-text">
                        <i class="fas fa-user-alt"></i>
                      </div>
                    </div>
                    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{old('name')}}">
                  </div>
                </div>
                <div class="form-group">
                  <label>Email</label>
                  @if (session('status'))
                  <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                  </div>
                  @endif
                  @error('email')
                  <div class="alert alert-danger" role="alert">
                    {{ $message }}
                  </div>
                  @enderror
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <div class="input-group-text">
                        <i class="fas fa-at"></i>
                      </div>
                    </div>
                    <input type="text" name="email" class="form-control" value="{{old('email')}}">
                  </div>
                </div>
                <div class="form-group">
                  <label>Level</label>
                  @if (session('status'))
                  <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                  </div>
                  @endif
                  @error('level')
                  <div class="alert alert-danger" role="alert">
                    {{ $message }}
                  </div>
                  @enderror
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <div class="input-group-text">
                        <i class="fas fa-award"></i>
                      </div>
                    </div>
                    <select type="text" name="level" class="form-control @error('level') is-invalid @enderror" value="{{old('level')}}">
                      <option value="" selected="">Select Level</option>
                      <option value="1">Administrator</option>
                      <option value="0">Author</option>
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label>Password</label>
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <div class="input-group-text">
                        <i class="fas fa-lock"></i>
                      </div>
                    </div>
                    <input type="password" name="password" data-indicator="pwindicator" class="form-control pwstrength @error('password') is-invalid @enderror">
                  </div>
                  <div id="pwindicator" class="pwindicator">
                    <div class="bar"></div>
                    <div class="label"></div>
                  </div>
                  @if (session('status'))
                  <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                  </div>
                  @endif
                  @error('password')
                  <div class="alert alert-danger" role="alert">
                    {{ $message }}
                  </div>
                  @enderror
                </div>
                <div class="form-group">
                  <button class="btn btn-success btn-icon btn-icon-left btn-block">
                    <i class="fas fa-flag"></i>
                    <span class="text">Buat Akun Baru</span>
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin-template.page')
@section('title', 'Accounts Edit')
@section('activeaccounts', 'active')
@section('content')
<!-- Page Heading -->
<div class="main-content">
  <section class="section">
    <div class="section-header">
      <h1>Accounts Edit</h1>
    </div>
    <div class="section-body">
      <div class="row">
        <div class="col-12">
          <div class="card">
            @if (session('success'))
            <div class="alert alert-success" role="alert">
              {{ session('success') }}
            </div>
            @endif
            @error('success')
            <div class="alert alert-danger" role="alert">
              {{ $message }}
            </div>
            @enderror
            <div class="card-header py-3">
              <a href="{{ route('webmanager.users.index') }}" class="btn btn-sm btn-primary btn-icon btn-icon-left">
                <span class="icon text-white-50">
                  <i class="fas fa-chevron-circle-left"></i>
                </span>
                <span class="text">Back</span>
              </a>  
            </div>
            <div class="card-body">
              <form method="POST" action=" {{ route('webmanager.users.update', $users->id) }} ">
                @csrf
                @method('put')
                <div class="form-group">
                  <label>Name</label>
                  @if (session('status'))
                  <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                  </div>
                  @endif
                  @error('name')
                  <div class="alert alert-danger" role="alert">
                    {{ $message }}
                  </div>
                  @enderror
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <div class="input-group-text">
                        <i class="fas fa-user-alt"></i>
                      </div>
                    </div>
                    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ $users->name }}" readonly>
                  </div>
                </div>
                <div class="form-group">
                  <label>Email</label>
                  @if (session('status'))
                  <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                  </div>
                  @endif
                  @error('email')
                  <div class="alert alert-danger" role="alert">
                    {{ $message }}
                  </div>
                  @enderror
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <div class="input-group-text">
                        <i class="fas fa-at"></i>
                      </div>
                    </div>
                    <input type="text" name="email" class="form-control" value="{{ $users->email }}">
                  </div>
                </div>
                <div class="form-group">
                  <label>Level</label>
                  @if (session('status'))
                  <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                  </div>
                  @endif
                  @error('level')
                  <div class="alert alert-danger" role="alert">
                    {{ $message }}
                  </div>
                  @enderror
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <div class="input-group-text">
                        <i class="fas fa-award"></i>
                      </div>
                    </div>
                    <select type="text" name="level" class="form-control @error('level') is-invalid @enderror" value="{{ $users->level }}">
                      @if($users->level == 1)
                        <option value="1" selected="">Administrator</option>
                        <option value="0">Author</option>
                      @else
                        <option value="1">Administrator</option>
                        <option value="0" selected="">Author</option>
                      @endif
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label>New Password</label>
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <div class="input-group-text">
                        <i class="fas fa-lock"></i>
                      </div>
                    </div>
                    <input type="password" name="password" data-indicator="pwindicator" class="form-control pwstrength">
                  </div>
                  <div id="pwindicator" class="pwindicator">
                    <div class="bar"></div>
                    <div class="label"></div>
                  </div>
                </div>
                <div class="form-group">
                  <button class="btn btn-success btn-icon btn-icon-left btn-block">
                    <i class="fas fa-flag"></i>
                    <span class="text">Save Changes</span>
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin-template.page')
@section('title', 'Accounts')
@section('activeaccounts', 'active')
@section('active_a_lists', 'active')
@section('content')

<!-- Page Heading -->
<div class="main-content">
  <section class="section">
    <div class="section-header">
      <h1>Accounts</h1>
    </div>
    <div class="section-body">
      <div class="row">
        <div class="col-12">
          <div class="card">
            @if (session('status'))
            <div class="alert alert-success" role="alert">
              {{ session('status') }}
            </div>
            @endif
            <div class="card-header py-3">
              <a href="{{ route('webmanager.users.create') }}" class="btn btn-sm btn-primary btn-icon btn-icon-left">
                <span class="icon text-white-50">
                  <i class="fas fa-user-plus"></i>
                </span>
                <span class="text">Add New</span>
              </a>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-striped table-hover" id="table-1">
                  <thead>
                    <tr>
                      <th width="5%" class="text-center">#</th>
                      <th>Name</th>
                      <th>Email</th>
                      <th class="text-center">Level</th>
                      <th width="10%" class="text-center">Action</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th width="5%" class="text-center">#</th>
                      <th>Name</th>
                      <th>Email</th>
                      <th class="text-center">Level</th>
                      <th width="10%" class="text-center">Action</th>
                    </tr>
                  </tfoot>
                  <tbody>
                    @foreach ($users as $result => $print)
                    <tr>
                      <td align="center">{{ $result + $users->firstitem() }}</td>
                      <td>{{ $print->name }}</td>
                      <td>{{ $print->email }}</td>
                      <td align="center">
                        <h6>
                          @if($print->level)
                            <span class="badge badge-primary">Administrator</span>
                          @else
                            <span class="badge badge-info">Author</span>
                          @endif
                        </h6>
                      </td>
                      <td align="center">
                        <form method="POST" action="{{ route('webmanager.users.destroy', $print->id) }}">
                          @csrf
                          @method('delete')
                          <a href="{{ route('webmanager.users.edit', $print->id) }}" class="btn btn-sm btn-warning btn-icon">
                            <span class="icon text-white-50">
                              <i class="fas fa-user-edit"></i>
                            </span>
                          </a>
                          <button type="submit" class="btn btn-sm btn-danger btn-icon">
                            <span class="icon text-white-50">
                              <i class="fas fa-user-times"></i>
                            </span>
                          </button>
                        </form>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
@endsection