routes/web.php
<?php

Auth::routes();

//================== This is for Front End ====================

// Landing Page
Route::get('/', function () {
	return view('front.landing');
});

// Blog
Route::get('/blog', 'BlogController@index');
Route::get('/blog/search', 'BlogController@search')->name('blog.search');
Route::get('/blog/luck', 'BlogController@luck')->name('blog.luck');
Route::get('/blog/category/{slug}', 'BlogController@category')->name('blog.category');
Route::get('/blog/tag/{slug}', 'BlogController@tag')->name('blog.tag');
Route::get('/blog/author/{id}', 'BlogController@author')->name('blog.author');
Route::get('/blog/{slug}', 'BlogController@show')->name('blog.details');

Route::get('/about', function () {
	return view('front.about');
});
Route::get('/contact', function () {
	return view('front.contact');
});

// Quick Links
Route::get('/license', function () {
	return view('front.license');
});
Route::get('/privacy-policy', function () {
	return view('front.privacy-policy');
});
Route::get('/contribute', function () {
	return view('front.contribute');
});

// Hall of Fame
Route::get('/report-bug', function () {
	return view('front.report-bug');
});
Route::get('/heroes', function () {
	return view('front.heroes');
});
Route::get('/patched', function () {
	return view('front.patched');
});



//================== This is for Back End ====================

Route::group(['middleware' => 'auth'], function()
{
	Route::get('/webmanager', 'WebManagerController@index')->name('webmanager');

	Route::get('/webmanager/posts/archived', 'PostsController@archived')->name('webmanager.posts.archived');
	Route::get('/webmanager/posts/restore/{id}', 'PostsController@restore')->name('webmanager.posts.restore');
	Route::delete('/webmanager/posts/clean/{id}', 'PostsController@clean')->name('webmanager.posts.clean');
	Route::delete('/webmanager/posts/massclean', 'PostsController@massclean')->name('webmanager.posts.massclean');

	Route::prefix('webmanager')->name('webmanager.')->group(function() {
   		Route::resource('tags','TagsController');
	});

	Route::prefix('webmanager')->name('webmanager.')->group(function() {
   		Route::resource('categories','CategoriesController');
	});

	Route::prefix('webmanager')->name('webmanager.')->group(function() {
   		Route::resource('posts','PostsController');
	});

	Route::prefix('webmanager')->name('webmanager.')->group(function() {
   		Route::resource('users','UsersController');
	});

	Route::prefix('webmanager')->name('webmanager.')->group(function() {
   		Route::resource('profiles','ProfilesController');
	});

	Route::prefix('webmanager')->name('webmanager.')->group(function() {
   		Route::resource('sites','SitesController');
	});

});

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Categories;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class CategoriesController extends Controller
{

    public function index()
    {
        $categories =  Categories::paginate();
        return view('admin.categories.index', compact('categories'));
    }


    public function create()
    {
        return view('admin.categories.create');
    }


    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|min:3'
        ]);
        
        Categories::create([
            'name' => $request->name,
            'slug' => Str::slug($request->name)
        ]);

        return redirect()->back()->with('success', 'New Category Saved!');
    }

    public function show(Categories $categories)
    {
        //
    }


    public function edit($id)
    {
        $category = Categories::findorfail($id);
        return view('admin.categories.edit', compact('category'));
    }


    public function update(Request $request, $id)
    {
        $this->validate($request, [
        	'name' => 'required|min:3'
        ]);

        $category_data = [
        	'name' => $request->name,
        	'slug' => Str::slug($request->name)
        ];

        Categories::whereId($id)->update($category_data);

        return redirect()->route('webmanager.categories.index')->with('status', 'Category Updated!');
    }


    public function destroy($id)
    {
    	$category = Categories::findorfail($id);
    	$category->delete();
        return redirect()->route('webmanager.categories.index')->with('status', 'Category Deleted!');
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin-template.page')
@section('title', 'New Kategori')
@section('activecategories', 'active')
@section('active_c_add', 'active')
@section('content')
<!-- Page Heading -->
<div class="main-content">
  <section class="section">
    <div class="section-header">
      <h1>New Category</h1>
    </div>
    <div class="section-body">
      <div class="row">
        <div class="col-12">
          <div class="card">
            @if (session('success'))
            <div class="alert alert-success" role="alert">
              {{ session('success') }}
            </div>
            @endif
            @error('success')
            <div class="alert alert-danger" role="alert">
              {{ $message }}
            </div>
            @enderror
            <div class="card-header py-3">
              <a href="{{ route('webmanager.categories.index') }}" class="btn btn-sm btn-primary btn-icon btn-icon-left">
                <span class="icon text-white-50">
                  <i class="fas fa-chevron-circle-left"></i>
                </span>
                <span class="text">Back</span>
              </a>  
            </div>
            <div class="card-body">
              <form method="POST" action=" {{ route('webmanager.categories.store') }} ">
                @csrf
                <div class="form-group">
                  <label>Category's Name</label>
                  @if (session('status'))
                  <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                  </div>
                  @endif
                  @error('name')
                  <div class="alert alert-danger" role="alert">
                    {{ $message }}
                  </div>
                  @enderror
                  <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{old('name')}}">
                </div>
                <div class="form-group">
                  <button class="btn btn-success btn-icon btn-icon-left btn btn-block">
                    <i class="fas fa-flag"></i>
                    <span class="text">Save New Category</span>
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin-template.page')
@section('title', 'Category Edit')
@section('activecategories', 'active')
@section('content')
<!-- Page Heading -->
<div class="main-content">
  <section class="section">
    <div class="section-header">
      <h1>Category Edit</h1>
    </div>
    <div class="section-body">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header py-3">
              <a href="{{ route('webmanager.categories.index') }}" class="btn btn-sm btn-primary btn-icon btn-icon-left">
                <span class="icon text-white-50">
                  <i class="fas fa-chevron-circle-left"></i>
                </span>
                <span class="text">Back</span>
              </a>  
            </div>
            <div class="card-body">
              <form action="{{ route('webmanager.categories.update', $category->id) }}" method="POST">
                @csrf
                @method('patch')
                <div class="form-group">
                  <label>Category Edit</label>
                  @error('name')
                  <div class="alert alert-danger" role="alert">
                    {{ $message }}
                  </div>
                  @enderror
                  <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ $category->name }}">
                </div>
                <div class="form-group">
                  <button class="btn btn-success btn-icon btn-icon-left btn-block">
                    <i class="fas fa-flag"></i>
                    <span class="text">Save Changes</span>
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin-template.page')
@section('title', 'Caregory')
@section('activecategories', 'active')
@section('active_c_lists', 'active')
@section('content')

<!-- Page Heading -->
<div class="main-content">
  <section class="section">
    <div class="section-header">
      <h1>Category</h1>
    </div>
    <div class="section-body">
      <div class="row">
        <div class="col-12">
          <div class="card">
            @if (session('status'))
            <div class="alert alert-success" role="alert">
              {{ session('status') }}
            </div>
            @endif
            <div class="card-header py-3">
              <a href="{{ route('webmanager.categories.create') }}" class="btn btn-sm btn-primary btn-icon btn-icon-left">
                <span class="icon text-white-50">
                  <i class="fas fa-flag"></i>
                </span>
                <span class="text">Add New</span>
              </a>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-striped table-hover" id="table-1">
                  <thead>
                    <tr>
                      <th width="5%" class="text-center">#</th>
                      <th>Name</th>
                      <th width="10%" class="text-center">Action</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th width="5%" class="text-center">#</th>
                      <th>Name</th>
                      <th width="10%" class="text-center">Action</th>
                    </tr>
                  </tfoot>
                  <tbody>
                    @foreach ($categories as $result => $print)
                    <tr>
                      <td align="center">{{ $result + $categories->firstitem() }}</td>
                      <td>{{ $print->name }}</td>
                      <td align="center">
                        <form method="POST" action="{{ route('webmanager.categories.destroy', $print->id) }}">
                          @csrf
                          @method('delete')
                          <a href="{{ route('webmanager.categories.edit', $print->id) }}" class="btn btn-sm btn-warning btn-icon">
                            <span class="icon text-white-50">
                              <i class="fas fa-edit"></i>
                            </span>
                          </a>
                          <button type="submit" class="btn btn-sm btn-danger btn-icon">
                            <span class="icon text-white-50">
                              <i class="fas fa-trash"></i>
                            </span>
                          </button>
                        </form>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
@endsection